import type { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import PageTitle from '../../components/PageTitle';
import RelatedProducts from '../../components/RelatedProducts';
import { ProductItemInterface } from '../../components/ProductItem';
import Image from 'next/image';
interface Props {
  productDetail: ProductItemInterface;
  relatedItems: ProductItemInterface[];
}
const ShopDetail: NextPage<Props> = ({ productDetail, relatedItems }) => {
  return (
    <>
      <Head>
        <title>Store - Shop Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={productDetail.title} />

      <section className="sec-product-detail bg0 p-t-65 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-6 col-lg-7 p-b-30">
              <div className="p-r-30 p-lr-0-lg">
                <div className="wrap-slick3 flex-sb flex-w">
                  <div className="slick3 gallery-lb">
                    <div className="item-slick3">
                      <div className="wrap-pic-w pos-relative">
                        <Image
                          src={productDetail.img}
                          alt="IMG-PRODUCT"
                          width="100%"
                          height="100%"
                          layout="responsive"
                          objectFit="contain"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="col-md-6 col-lg-5 p-b-30">
              <div className="p-r-50 p-t-5 p-lr-0-lg">
                <h4 className="mtext-105 cl2 js-name-detail p-b-14">
                  {productDetail.title}
                </h4>

                <span className="mtext-106 cl2">{productDetail.price}</span>

                <p className="stext-102 cl3 p-t-23">
                  {productDetail.description}
                </p>

                <div className="flex-w flex-m p-l-100 p-t-40 respon7">
                  <div className="flex-m bor9 p-r-10 m-r-11">
                    <a
                      href="#"
                      className="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100"
                      data-tooltip="Add to Wishlist"
                    >
                      <i className="zmdi zmdi-favorite"></i>
                    </a>
                  </div>

                  <a
                    href="#"
                    className="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
                    data-tooltip="Facebook"
                  >
                    <i className="fa fa-facebook"></i>
                  </a>

                  <a
                    href="#"
                    className="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
                    data-tooltip="Twitter"
                  >
                    <i className="fa fa-twitter"></i>
                  </a>

                  <a
                    href="#"
                    className="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100"
                    data-tooltip="Google Plus"
                  >
                    <i className="fa fa-google-plus"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>

          <div className="bor10 m-t-50 p-t-43 p-b-40">
            <div className="tab01">
              <div className="tab-content p-t-43">
                <div
                  className="tab-pane fade show active"
                  id="description"
                  role="tabpanel"
                >
                  <div className="how-pos2 p-lr-15-md">
                    <p className="text-102 cl6">{productDetail.description}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="bg6 flex-c-m flex-w size-302 m-t-73 p-tb-15">
          <span className="stext-107 cl6 p-lr-25">
            Free shipping - only today
          </span>
        </div>
      </section>

      <RelatedProducts relatedItems={relatedItems} />
    </>
  );
};
export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch('https://graceful-bead-song.glitch.me/products');
  const data: ProductItemInterface[] = await res.json();
  const paths = data.map((postDetail) => ({
    params: {
      id: postDetail.id.toString(),
    },
  }));
  return {
    paths,
    fallback: false,
  };
};
export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params && params.id) {
    const res = await fetch(
      `https://graceful-bead-song.glitch.me/products/${params.id}`
    );
    const productDetail = await res.json();
    const randomNo = Math.floor(Math.random() * 6);

    const resRelatedItems = await fetch(
      `https://graceful-bead-song.glitch.me/products?_start=${randomNo}&_limit=4`
    );
    const relatedItems = await resRelatedItems.json();

    return {
      props: {
        productDetail,
        relatedItems,
      },
    };
  }

  return {
    props: {},
  };
};

export default ShopDetail;
