import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import BlogItem, { BlogItemInterface } from '../../components/BlogItem';
import PageTitle from '../../components/PageTitle';
import { useRouter } from 'next/router';
interface Props {
  blogs: BlogItemInterface[];
}
const Blog: NextPage<Props> = ({ blogs }) => {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState<string>('');
  const { asPath } = useRouter();
  const onSearchSubmit = (e: any) => {
    e.preventDefault();
    if (searchQuery.length < 3) {
      return;
    }
    router.push({
      query: {
        ...router.query,
        q: searchQuery,
      },
    });
  };
  useEffect(() => {
    if (router.query.q) {
      setSearchQuery(router.query.q.toString());
    }
  }, [router.query]);
  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {blogs ? (
                  blogs.map((blog) => (
                    <BlogItem blogData={blog} key={blog.id} />
                  ))
                ) : (
                  <p>No results match your search.</p>
                )}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form className="bor17 of-hidden pos-relative">
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search"
                  />

                  <button
                    className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04"
                    onClick={onSearchSubmit}
                  >
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li
                      className={`bor18 ${
                        asPath === '/blog?category=fashion' &&
                        `filter-link-active`
                      }`}
                    >
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            query: {
                              category: 'fashion',
                            },
                          });
                          setSearchQuery('');
                        }}
                      >
                        Fashion
                      </button>
                    </li>

                    <li
                      className={`bor18 ${
                        asPath === '/blog?category=beauty' &&
                        `filter-link-active`
                      }`}
                    >
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            query: {
                              category: 'beauty',
                            },
                          });
                          setSearchQuery('');
                        }}
                      >
                        Beauty
                      </button>
                    </li>

                    <li
                      className={`bor18 ${
                        asPath === '/blog?category=streetstyle' &&
                        `filter-link-active`
                      }`}
                    >
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4 "
                        onClick={() => {
                          router.push({
                            query: {
                              category: 'streetstyle',
                            },
                          });
                          setSearchQuery('');
                        }}
                      >
                        Street Style
                      </button>
                    </li>

                    <li
                      className={`bor18 ${
                        asPath === '/blog?category=lifestyle' &&
                        `filter-link-active`
                      }`}
                    >
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            query: {
                              category: 'lifestyle',
                            },
                          });
                          setSearchQuery('');
                        }}
                      >
                        Life Style
                      </button>
                    </li>

                    <li
                      className={`bor18 ${
                        asPath === '/blog?category=diy%26crafts' &&
                        `filter-link-active`
                      }`}
                    >
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => {
                          router.push({
                            query: {
                              category: 'diy&crafts',
                            },
                          });
                          setSearchQuery('');
                        }}
                      >
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { category, q } = query;
  if (q) {
    const res = await fetch(
      `https://graceful-bead-song.glitch.me/blogs?q=${q}`
    );
    const blogs = await res.json();
    return {
      props: {
        blogs,
      },
    };
  }
  if (q && category) {
    const res = await fetch(
      `https://graceful-bead-song.glitch.me/blogs?category_like=${category}&q=${q}`
    );
    const blogs = await res.json();
    return {
      props: {
        blogs,
      },
    };
  }
  const res = await fetch(
    `https://graceful-bead-song.glitch.me/blogs${
      category ? `?category_like=${category}` : ''
    } 
   
    `
  );
  const blogs = await res.json();

  return {
    props: {
      blogs,
    },
  };
};

export default Blog;
