import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Banner, { BannerInterface } from '../components/Banner';
import CategoryPicker from '../components/CategoryPicker';
import FeaturedBlogs from '../components/FeaturedBlogs';
import FeaturedProducts from '../components/FeaturedProducts';
import { ProductItemInterface } from '../components/ProductItem';
import { BlogItemInterface } from '../components/BlogItem';
interface Props {
  banner_cont: BannerInterface;
  featuredProd: ProductItemInterface[];
  featuredBlogs: BlogItemInterface[];
}
const Home: NextPage<Props> = ({
  banner_cont,
  featuredProd,
  featuredBlogs,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner preTitle={banner_cont.preTitle} title={banner_cont.title} />

      <CategoryPicker />

      <FeaturedProducts featuredProd={featuredProd} />

      <FeaturedBlogs featuredBlogs={featuredBlogs} />
    </>
  );
};
export const getStaticProps: GetStaticProps = async () => {
  const resBanner = await fetch(
    'https://graceful-bead-song.glitch.me/banner_content'
  );
  const banner_cont = await resBanner.json();

  const resFeaturedProd = await fetch(
    'https://graceful-bead-song.glitch.me/products/?_limit=4'
  );
  const featuredProd = await resFeaturedProd.json();

  const resFeaturedBlogs = await fetch(
    'https://graceful-bead-song.glitch.me/blogs/?_limit=3'
  );
  const featuredBlogs = await resFeaturedBlogs.json();

  return {
    props: {
      banner_cont,
      featuredProd,
      featuredBlogs,
    },
  };
};

export default Home;
